#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

get_cert() {
  #TODO: get certificate here
  echo "should get certificate..."
}

start_service() {
  [ ! -f /etc/sentinel/router.crt ] && get_cert
  procd_open_instance
  procd_set_param command /usr/bin/sentinel-proxy
  procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_close_instance
}

